# Generated by Django 5.0.6 on 2024-07-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginanalysis',
            name='plugin_name',
            field=models.CharField(default='default_plugin_name', max_length=255),
        ),
    ]
