# Generated by Django 5.0.6 on 2024-07-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0004_pluginanalysis_plugin_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemoryDump',
        ),
        migrations.AlterField(
            model_name='pluginanalysis',
            name='plugin_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
