# Generated by Django 5.0.6 on 2024-07-14 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0005_delete_memorydump_alter_pluginanalysis_plugin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryDump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='memory_dumps/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='pluginanalysis',
            name='memory_dump',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='plugin.memorydump'),
        ),
    ]
